/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
 /*\title Blinky LED
 * \abstract An LED is blinking based on the timing given by a wait function.
 * \description A wait function is used to add delays between switching on and switching off an LED
 *              on port pin P00.5.
 *
 * \name Blinky_LED_1_KIT_TC275_LK
 * \version V1.0.2
 * \board AURIX TC275 lite Kit, KIT_AURIX_TC275_LITE, TC27xTP_D-Step
 * \keywords AURIX, Blinky_LED_1, Blinky, LED, Lite
 * \documents https://www.infineon.com/aurix-expert-training/Infineon-AURIX_Blinky_LED_1_KIT_TC275_LK-TR-v01_00_02-EN.pdf
 * \documents https://www.infineon.com/aurix-expert-training/TC27D_iLLD_UM_1_0_1_12_0.chm
 * \lastUpdated 2021-06-29
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxScuWdt.h"
#include "IfxStm_Timer.h"
#include "IfxAsclin_Asc.h"
#include "IfxPort.h"
#include "IfxPort_PinMap.h" // 핀맵 헤더를 포함

#define LED_PIN    IfxPort_P00_5 // 핀맵을 사용하여 LED 핀 정의

Ifx_STM *stmSfr = &MODULE_STM0; // STM 모듈 사용

IfxAsclin_Asc asc;
char sendString[] = "Hello, LED!"; // 송신할 문자열
char receiveBuffer[32]; // 수신할 문자열을 저장할 버퍼
volatile boolean sendFlag = FALSE;

void delayMilliseconds(uint32 milliseconds)
{
    Ifx_TickTime ticks = IfxStm_getTicksFromMilliseconds(stmSfr, milliseconds);
    IfxStm_waitTicks(stmSfr, ticks); // 밀리초 기반 대기 함수
}

void initUART(void)
{
    IfxAsclin_Asc_Config ascConfig;
    IfxAsclin_Asc_initModuleConfig(&ascConfig, &MODULE_ASCLIN0); // ASCLIN0 모듈 사용
    ascConfig.baudrate.baudrate = 115200; // 전송 속도 설정
    IfxAsclin_Asc_initModule(&asc, &ascConfig); // UART 모듈 초기화
}

void sendUARTString(const char *data)
{
    const char *p = data;
    while (*p)
    {
        IfxAsclin_Asc_write8(&asc, *p); // UART를 통해 문자 전송
        p++;
    }
}

void receiveUARTString(char *buffer)
{
    uint32 i = 0;
    while (1)
    {
        while (IfxAsclin_Asc_getReadCount(&asc) == 0); // 문자 수신까지 대기
        buffer[i] = IfxAsclin_Asc_read8(&asc); // 수신 문자 버퍼에 저장
        if (buffer[i] == '\0' || buffer[i] == '\n' || buffer[i] == '\r')
        {
            buffer[i] = '\0';
            break; // 종료 문자 수신시 수신 루프 종료
        }
        i++;
    }
}

int core0_main(void)
{
    uint32 i = 0; // 'i' 변수 정의

    IfxCpu_enableInterrupts(); // CPU 인터럽트 활성화

    initUART(); // UART 초기화

    IfxPort_setPinModeOutput(LED_PIN.port, LED_PIN.pinIndex, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    // LED 핀을 push-pull 출력 모드로 설정

    while (1)
    {
        sendFlag = TRUE; // 플래그 TRUE로 설정

        sendUARTString(sendString); // 문자열 송신
        IfxPort_setPinState(LED_PIN.port, LED_PIN.pinIndex, IfxPort_State_high);

        delayMilliseconds(1000); // 1000밀리초(1초) 대기

        sendFlag = FALSE; // 플래그 FALSE로 설정
        IfxPort_setPinState(LED_PIN.port, LED_PIN.pinIndex, IfxPort_State_low);

        receiveUARTString(receiveBuffer); // 송신된 문자열 수신 및 버퍼에 저장

        IfxAsclin_Asc_write8(&asc, '\n'); // 개행 문자 출력
        IfxAsclin_Asc_write8(&asc, 'R'); // Echo 수신 루프 시작 문자 출력
        IfxAsclin_Asc_write8(&asc, '\0'); // 문자열 끝
        delayMilliseconds(100); // 100밀리초 대기

        i = 0; // 'i'를 0으로 초기화
        while (receiveBuffer[i] != '\0')
        {
            IfxAsclin_Asc_write8(&asc, receiveBuffer[i]); // 수신된 문자열 출력
            i++;
        }

        delayMilliseconds(1000); // 1000밀리초(1초) 대기
    }

    return (1);
}

